[workspace]
members = [
    "crates/lexer",
    "crates/parser",
    "crates/ast",
    "crates/ir",
    "crates/analyzer",
    # "crates/codegen",
    "tools/pinec", "crates/utils", "crates/linker",
]
